### Base travis config file
language: ruby
#cache: bundler
sudo: false
exclude: [vendor]
rvm:
- 2.2
script: scripts/buildJekyll.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    "scripts/uploadViaFTP.sh"
    fi
