### Base travis config file
language: ruby
#cache: bundler
sudo: false
exclude: [vendor]
rvm:
- 2.2
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site/index.html
after_success:
  - echo "$TRAVIS_BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    scripts/uploadViaFTP.sh;
    fi
