---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge
exclude: [vendor]


### content configuration ###
title:       "Aikido of Northern Virginia"
keywords:    "aikido, ASU, northern virginia, asu, aikido schools of ueshiba, ueshiba, virginia, northern"
description: "Aikido of Northern Virginia, located across the street from Ballston metro station in Arlington, Northern VA, is a traditional aikido dojo afiliated to aikikai hombu dojo through the aikido schools of Ueshiba."
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.png"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: 'UA-64055663-1' ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  gray:     '#CAC6C4'
  gray-orange: '#D3CBC7'
  gray-blue:   '#B6C5CB'
  gray-green:  '#C3CFC4'

icon:
  contact: fa-phone
  directions: fa-map-marker
  schedule: fa-calendar
  staff: fa-university
  metro: fa-train
  seminar: fa-calendar-plus-o

kramdown:
  auto_ids:  false
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
